# Generated by Django 2.1.2 on 2019-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('qq', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='用户QQ')),
                ('status', models.CharField(max_length=5, verbose_name='用户状态')),
            ],
            options={
                'verbose_name_plural': '用户状态',
            },
        ),
    ]
